pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'node:18-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:18-alpine' }
      }
      steps {
        sh 'node --version'
        sh 'npm install -g @angular/cli'
        sh 'ng --version'
      }
    }
  }
}